from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / '2927547.png'

# sizing

BIG_FONT_SIZE = 18
MEDIUM_FONT_SIZE = 16
SMALL_FONT_SIZE = 12
TEXT_MARGIN = 10
MINIMUM_WIDTH = 600

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
